backend:
  name: git-gateway
  branch: dev

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "insights"
    label: "Insights"
    folder: "src/content/insights"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Published Date", name: "pubDate", widget: "datetime" }
      - { label: "Updated Date", name: "updatedDate", widget: "datetime", required: false }
      - { label: "Hero Image URL", name: "heroImage", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }